### ISSUE TITLE
batch_size works in Eval ? (16个batchsize的设置好像没起作用）

### ISSUE THREAD

**Issue by Lg955** [yijingru/BBAVectors-Oriented-Object-Detection#104]
In Evaluatation, the 16 batch_size and multi-gpus is not used. In the code, a single img is pred each loop.
https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/7efd410f5f4ded94aca986aeb0bd1292235d1314/func_utils.py#L58

**Comment by yijingru** [comment]
correct!
