### ISSUE TITLE
Maybe a error about heatmap

### ISSUE THREAD

**Issue by Lg955** [yijingru/BBAVectors-Oriented-Object-Detection#106]
In  this code, No variable accepts return value:
https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/7efd410f5f4ded94aca986aeb0bd1292235d1314/datasets/base.py#L184
So the "**hm**"  is zeros all the time?
https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/7efd410f5f4ded94aca986aeb0bd1292235d1314/datasets/base.py#L246

![heatmap ](https://user-images.githubusercontent.com/69025725/128118869-39785fe9-3ab5-4754-87a2-658dc7bbcf62.png)

**Comment by yijingru** [comment]
it's in-place, you may visualize using cv2.imshow(normalization(hm)*255)

**Comment by Lg955** [comment]
> it's in-place, you may visualize using cv2.imshow(normalization(hm)*255)

OK,I will try it after the training, thank U!

**Comment by Lg955** [comment]
I check the heatmap in two places(both in `datasets/base.py` ):
 1.
![hm1](https://user-images.githubusercontent.com/69025725/128654694-f3aee378-e64a-4625-a9cd-cafc7314f8ed.png)
 the result is:
![hm2](https://user-images.githubusercontent.com/69025725/128654713-09a4ad51-6b30-472a-bb71-5d88c23bfd34.png)

 2.
![hm4](https://user-images.githubusercontent.com/69025725/128654745-25fd13ed-0920-4c65-bb10-3d5242ba5530.png)
 the result is: (the bottom left maybe a correct heatmap)
![hm3](https://user-images.githubusercontent.com/69025725/128654753-c33dcf92-af49-4068-b6db-bbbb5e500309.png)

So I want to know whether my method and result are correct?

**Comment by yijingru** [comment]
As far as I know, `draw_umich_gaussian()` is fine to create ground truth. But you can make it return to ensure correctness.
