### ISSUE TITLE
ModuleNotFoundError: No module named 'dota_kit'

### ISSUE THREAD

**Issue by lihlong** [yijingru/BBAVectors-Oriented-Object-Detection#128]

**Comment by lihlong** [comment]
我下载DOTA_devkit到datasets目录里，然后也把里面setup.py中要用到的包都pip install了，然后他说要下载swig工具也下载并且添加到环境目录了；然后我以为一切都配置好了，就在终端输入：python main.py --data_dir dataPath --epochs 80 --batch_size 16 --dataset dota --phase train，然后他报错说没有叫dota_kit的module，于是我去DOTA_devkit中看了一下，确实没找到dota_kit这个东东，请问有朋友知道是咋回事吗，孩子要emo了55

**Comment by lihlong** [comment]
oh，i just update the name and reopen the pycharm, and then it's done

**Comment by aqsc** [comment]
How do you update the name? I have also encountered this problem.

**Comment by 123comeon123** [comment]
作者，解决了吗
