### ISSUE TITLE
ModuleNotFoundError: No module named 'dota_kit' 

### ISSUE THREAD

**Issue by aqsc** [yijingru/BBAVectors-Oriented-Object-Detection#130]
after I put the 'DOTA_devkit' under dataset and run the train.py, it will exposure one error ModuleNotFoundError: No module named 'dota_kit' when  import dota_kit.dota_utils as util.
How to solve this?

**Comment by SuperPC328** [comment]
I meet the same problem, cloud you tell me what's you solvtion?
