### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by varshhh3** [yijingru/BBAVectors-Oriented-Object-Detection#14]
**!python main.py --data_dir='/content/drive/My Drive/Bba' --num_epoch=80 --batch_size=16 --dataset=dota --phase=train**
File "main.py", line 6, in <module>
    from datasets.dataset_hrsc import HRSC
  File "/content/BBAVectors-Oriented-Object-Detection/datasets/dataset_hrsc.py", line 6, in <module>
    from .DOTA_devkit.hrsc_evaluation_task1 import voc_eval
ModuleNotFoundError: No module named 'datasets.DOTA_devkit.hrsc_evaluation_task1'
![er](https://user-images.githubusercontent.com/41830460/94653119-b07ccf00-0318-11eb-8040-b3da585f122c.png)

**Comment by yijingru** [comment]
Duplicate of #9 , you have to download `DOTA_devkit` first.

**Comment by varshhh3** [comment]
> Duplicate of #9 , you have to download `DOTA_devkit` first.

Will follow that up ! Thanks
