### ISSUE TITLE
DOTA v1.0 test results achieved 0.620, a little far from 0.723

### ISSUE THREAD

**Issue by Tarazed** [yijingru/BBAVectors-Oriented-Object-Detection#2]
Hello,
I have trained the model followed by your settings with a batch size of 20 on 4 RTX 2080Ti GPUs. I cropped the images into 600x600 with a stride of 100 using ImgSpit_multi_process.py of the official repo, but only got 54717 images on trainval when preserving negative samples with no objects in them. Finally after 40 epochs of training, I got mAP of 61.95 on test dataset, a little far from 72.32 showed in the paper. Can you help me with that? Besides, I can't got 69377 cropped images of trainval set. Thank you.

**Comment by zhangyuxuan1996** [comment]
> Hello,
> I have trained the model followed by your settings with a batch size of 20 on 4 RTX 2080Ti GPUs. I cropped the images into 600x600 with a stride of 100 using ImgSpit_multi_process.py of the official repo, but only got 54717 images on trainval when preserving negative samples with no objects in them. Finally after 40 epochs of training, I got mAP of 61.95 on test dataset, a little far from 72.32 showed in the paper. Can you help me with that? Besides, I can't got 69377 cropped images of trainval set. Thank you.

请问怎么测试的？ https://captain-whu.github.io/DOTA/evaluation.html 这个网址点不开咋回事？

**Comment by Tarazed** [comment]
是这个网址，服务器不是很稳定

**Comment by zhangyuxuan1996** [comment]
> 是这个网址，服务器不是很稳定
可能batchsize比原文大，效果会相对好一点。
- mAP: 0.7386079289654184
- ap of each class: plane:0.8906786852353635, baseball-diamond:0.7973180557325118, bridge:0.49555937732787664, ground-track-field:0.6652836232472856, small-vehicle:0.7719567850263218, large-vehicle:0.8127366944445986, ship:0.8785596536225615, tennis-court:0.9087453350749631, basketball-court:0.86021476336708, storage-tank:0.8668640701621114, soccer-ball-field:0.5594583780845677, roundabout:0.6310733396356176, harbor:0.6609224804633762, swimming-pool:0.6937428143102882, helicopter:0.5860048787467512

**Comment by yijingru** [comment]
> > 是这个网址，服务器不是很稳定
> > 可能batchsize比原文大，效果会相对好一点。
> 
> * mAP: 0.7386079289654184
> * ap of each class: plane:0.8906786852353635, baseball-diamond:0.7973180557325118, bridge:0.49555937732787664, ground-track-field:0.6652836232472856, small-vehicle:0.7719567850263218, large-vehicle:0.8127366944445986, ship:0.8785596536225615, tennis-court:0.9087453350749631, basketball-court:0.86021476336708, storage-tank:0.8668640701621114, soccer-ball-field:0.5594583780845677, roundabout:0.6310733396356176, harbor:0.6609224804633762, swimming-pool:0.6937428143102882, helicopter:0.5860048787467512

It's amazing. Can you share the training batch size?

**Comment by Tarazed** [comment]
> > 是这个网址，服务器不是很稳定
> > 可能batchsize比原文大，效果会相对好一点。
> 
> * mAP: 0.7386079289654184
> * ap of each class: plane:0.8906786852353635, baseball-diamond:0.7973180557325118, bridge:0.49555937732787664, ground-track-field:0.6652836232472856, small-vehicle:0.7719567850263218, large-vehicle:0.8127366944445986, ship:0.8785596536225615, tennis-court:0.9087453350749631, basketball-court:0.86021476336708, storage-tank:0.8668640701621114, soccer-ball-field:0.5594583780845677, roundabout:0.6310733396356176, harbor:0.6609224804633762, swimming-pool:0.6937428143102882, helicopter:0.5860048787467512

最后我的mAP是69.97，40个epoch时loss还有下降空间，我再继续训练看看

**Comment by Tarazed** [comment]
和paper中的结果相比，有的类别有上升而有的类别有较大下降

**Comment by zhangyuxuan1996** [comment]
> 和paper中的结果相比，有的类别有上升而有的类别有较大下降

好的，你再试一下，我上面的结果没有改什么，你有在HRSC的数据集上run吗? 我跑的结果 epoch=100(只用训练集map87.6/88.15两次结果，训练集+测试集map89.14)。感觉波动性挺大的，作者的意思应该是只用了训练集(paper,88.6)

**Comment by yijingru** [comment]
> 和paper中的结果相比，有的类别有上升而有的类别有较大下降

你可以把 --conf_thresh调低一点，0.1或者0.05

**Comment by Tarazed** [comment]
> > 和paper中的结果相比，有的类别有上升而有的类别有较大下降
> 
> 你可以把 --conf_thresh调低一点，0.1或者0.05

You are right. After I changed the conf_thresh from 0.18 to 0.1, the mAP increased to 71.32.

**Comment by Tarazed** [comment]
> > 和paper中的结果相比，有的类别有上升而有的类别有较大下降
> 
> 好的，你再试一下，我上面的结果没有改什么，你有在HRSC的数据集上run吗? 我跑的结果 epoch=100(只用训练集map87.6/88.15两次结果，训练集+测试集map89.14)。感觉波动性挺大的，作者的意思应该是只用了训练集(paper,88.6)

HRSC还没跑，感觉跟数据关系挺大的

**Comment by yijingru** [comment]
> > > 和paper中的结果相比，有的类别有上升而有的类别有较大下降
> > 
> > 
> > 你可以把 --conf_thresh调低一点，0.1或者0.05
> 
> You are right. After I changed the conf_thresh from 0.18 to 0.1, the mAP increased to 71.32.

You can also increase the batch_size, I got mAP of 74.92 after using batch_size = 48 on 4 RTX6000.

**Comment by 18804601171** [comment]
@zhangyuxuan1996 我在训练hrsc后，测试的可视化效果里边界框都是平行四边形，而不是像gt那样的旋转矩形框，是怎么回事呢，请问你在训练后测试可视化有没有遇到同样的情况呢

**Comment by byfate** [comment]
> > 和paper中的结果相比，有的类别有上升而有的类别有较大下降
> 
> 好的，你再试一下，我上面的结果没有改什么，你有在HRSC的数据集上run吗? 我跑的结果 epoch=100(只用训练集map87.6/88.15两次结果，训练集+测试集map89.14)。感觉波动性挺大的，作者的意思应该是只用了训练集(paper,88.6)

您好 我想问下这个HRSC数据集上跑的时候需要crop吗？然后数据splidata需要0.5吗 谢谢

**Comment by igo312** [comment]
I get the mAP 69.01 after using batch_size = 64 on 8 V100. the lr_rate is  2e-4, I trained it with 60 epoch and using the learning schedule as shown below:
```
        self.scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(self.optimizer, mode='min', factor=0.5, patience=5)
```
The conf_thresh is 0.18
