### ISSUE TITLE
Where are the text files for load_img_ids in dataset_dota.py? 

### ISSUE THREAD

**Issue by jeonghwaYoo** [yijingru/BBAVectors-Oriented-Object-Detection#27]
https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/e070d39bec96811378eb00a33d0e3969ed7be352/datasets/dataset_dota.py#L47-L56

I'm really thank you for your sharing! 
I have one question.
Where are the text files for  `load_img_ids` in `dataset_dota.py`? 
Since this file was not found, I manually created a file containing path information.
But this causes problems in `ResultMerge_multi_process.py`.
I think it is because the file name is different. 
In this code, the x and y coordinates are included in the file name., but I can't figure out where to find that information.
How can I solve this issue? 

Thank you!

**Comment by yijingru** [comment]
I see. You probably need to split the original data first using the tools in `ImgSplit_multi_process.py` under `DOTA_devkit` to generate `trainval.txt` and `test.txt`. I used the following in `ImgSplit_multi_process.py`
```
    split = splitbase(r'../OriginalData/train',
                       r'../train',
                      gap=100,
                      subsize=600,
                      num_process=8
                      )
    split.splitdata(1)
    split.splitdata(0.5)
```

**Comment by jeshy** [comment]
split = splitbase(r'../dota/train',
                       r'../dota/trainsplit',
                      gap=200,
                      subsize=1024,
                      num_process=8
                      )
    split.splitdata(1)
    split.splitdata(0.5)
# no trainval.txt in ../dota or ../dota/trainsplit
how to do...

**Comment by yijingru** [comment]
> ```
> split = splitbase(r'../dota/train',
>                    r'../dota/trainsplit',
>                   gap=200,
>                   subsize=1024,
>                   num_process=8
>                   )
> split.splitdata(1)
> split.splitdata(0.5)
> ```
> 
> # no trainval.txt in ../dota or ../dota/trainsplit
> how to do...

Run `ImgSplit_multi_process.py` you will have the split datasets in `images` and `labelTxt`. You can gather the names in `images` and save the list of names without suffix to `xx.txt`, depending on which dataset you are splitting.

**Comment by jeonghwaYoo** [comment]
@jeshy Thank you!!
