### ISSUE TITLE
关于测试的问题

### ISSUE THREAD

**Issue by wenliangsun** [yijingru/BBAVectors-Oriented-Object-Detection#37]
你好，我想问一下，你在测试和验证的时候有对图像进行裁剪吗？我用你的代码跑了dota，evaluate的时候，会生成result_data,但是在merge的时候会报错，我看result_data 中生成的文件是merge之后的，所以，你在evaluate的时候有对图像裁剪吗？是使用的原图测试的吗？

**Comment by yijingru** [comment]
The model was fed with cropped images.
