### ISSUE TITLE
HRSC2016 dataset

### ISSUE THREAD

**Issue by hust-kevin** [yijingru/BBAVectors-Oriented-Object-Detection#40]
can you provide the HRSC2016 dataset download url. The url in HRSC2016 (http://www.escience.cn/people/liuzikun/DataSet.html) can not be found.

**Comment by yijingru** [comment]
https://www.kaggle.com/guofeng/hrsc2016

**Comment by hust-kevin** [comment]
thanks，can you provide some annotations in `data_transform` function,  can't understand the detail of the code
