### ISSUE TITLE
您好，我想问问heatmap的问题

### ISSUE THREAD

**Issue by Eliclx** [yijingru/BBAVectors-Oriented-Object-Detection#44]
您好，我成功使用了您公开的代码完成了效果复现，效果很好，非常感谢！
我是一名初学者，您论文中通过heatmap找到了物体的中心点，对此我不是理解：

> 不明白文中heatmap是怎么样生成的(heatmap通道代表类别数情况下，每个通道是通过什么方式使其只生成当前类的物体的heatmap)，我在源码中没能找到heatmap的生成代码(可能晚辈能力不够)，可否指点一下或者推荐几篇相关论文。

十分感谢！！

**Comment by yijingru** [comment]
你可以看看这篇 [CornerNet](https://arxiv.org/pdf/1808.01244.pdf)

**Comment by Eliclx** [comment]
好的，谢谢您

**Comment by KeVincechen** [comment]
> 您好，我成功使用了您公开的代码完成了效果复现，效果很好，非常感谢！
> 我是一名初学者，您论文中通过heatmap找到了物体的中心点，对此我不是理解：
> 
> > 不明白文中heatmap是怎么样生成的(heatmap通道代表类别数情况下，每个通道是通过什么方式使其只生成当前类的物体的heatmap)，我在源码中没能找到heatmap的生成代码(可能晚辈能力不够)，可否指点一下或者推荐几篇相关论文。
> 
> 十分感谢！！

请问您复现是自己训练过dota数据了么，那么数据标签格式是怎样的呢，如class，c,bbox，w,h,a这样的形式

**Comment by yijingru** [comment]
> > 您好，我成功使用了您公开的代码完成了效果复现，效果很好，非常感谢！
> > 我是一名初学者，您论文中通过heatmap找到了物体的中心点，对此我不是理解：
> > > 不明白文中heatmap是怎么样生成的(heatmap通道代表类别数情况下，每个通道是通过什么方式使其只生成当前类的物体的heatmap)，我在源码中没能找到heatmap的生成代码(可能晚辈能力不够)，可否指点一下或者推荐几篇相关论文。
> > 
> > 
> > 十分感谢！！
> 
> 请问您复现是自己训练过dota数据了么，那么数据标签格式是怎样的呢，如class，c,bbox，w,h,a这样的形式

Example in Dota:`315.0 337.0 314.0 333.0 320.0 327.0 322.0 333.0 small-vehicle`, pt1,pt2,pt3,pt4,class
