### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by s-s-wang** [yijingru/BBAVectors-Oriented-Object-Detection#48]
After executive the train command, it report error "RuntimeError: CUDA out of memory. Tried to allocate 182.00 MiB (GPU 0; 7.79 GiB total capacity; 6.52 GiB already allocated; 127.31 MiB free; 69.56 MiB cached)".

**Comment by Amberrferr** [comment]
> 

did you solve that? if yes, could you please tell me how you solved it? (reduce the batch size?）
