### ISSUE TITLE
HRSC2016 download link

### ISSUE THREAD

**Issue by byfate** [yijingru/BBAVectors-Oriented-Object-Detection#49]
Thank you for your wonderful work,I was wondering if you can give me the HRSC2016 dataset download link， I can not find the download linke on the Internet. Appreciate!

**Comment by byfate** [comment]
I have found it in the https://aistudio.baidu.com/aistudio/datasetlist/2

**Comment by Luiweony** [comment]
@byfate This link is invalid. Could you please send another link of HRSC2016 data set?Thank you very much!

**Comment by BakingBrains** [comment]
@Luiweony here it is,
[https://aistudio.baidu.com/aistudio/datasetdetail/75485](https://aistudio.baidu.com/aistudio/datasetdetail/75485)
