### ISSUE TITLE
 About bl tl tr br return by cv2.points

### ISSUE THREAD

**Issue by byfate** [yijingru/BBAVectors-Oriented-Object-Detection#51]
I have read the code about generating the groud truth,and I visiual the image and plot bl tl tr br points in original image.
I found that the bl point is not always the bottom left. It will change with the change of x,y w,h ,theta.I am wondering if you can help me in this problem.Does it will affct the definition in the paper, I am little confused.

**Comment by yijingru** [comment]
When you plot the `t,r,b,l` and look them in a `quadrant` way, then you will find it's right. You can look at Fig.2, when you rotate the box anticlockwise, the `bl` will become `br`. By the way, I don't really think the name of the vector matters, they are just four types, as long as the four types can be differentiated by ground-truth, it will be fine.

**Comment by byfate** [comment]
OK I get it,appreciated. It actually will change when rotate them, thank your awesome work.

**Comment by byfate** [comment]
OK I get it,appreciated. It actually will change when rotate them, thank your awesome work.
