### ISSUE TITLE
How to generate HRSC datasets

### ISSUE THREAD

**Issue by byfate** [yijingru/BBAVectors-Oriented-Object-Detection#52]
Sorry to bother you, I have a question whether the HRSC datasets just resize to 600*600 or 608*608,or follow the Dota datasets,using splitdata(1) and slitdata(0) with crop size 600*600,stride 100 ,Thank you

**Comment by yijingru** [comment]
Since HRSC images are in a smaller size, we don't need to split them. You can check details in `4.1 Datasets` in the paper.

**Comment by byfate** [comment]
OK , I got it. you just resize to 608*608 ，am I right ?hhh

**Comment by yijingru** [comment]
> OK , I got it. you just resize to 608*608 ，am I right ?hhh

right

**Comment by byfate** [comment]
Thanks for replying

**Comment by Luiweony** [comment]
@byfate  How do you convert the HRSC data set to the format required by the code?Hope to get your reply. Thank you!
