### ISSUE TITLE
RuntimeError: The size of tensor a (15) must match the size of tensor b (5) at non-singleton dimension 1

### ISSUE THREAD

**Issue by s-s-wang** [yijingru/BBAVectors-Oriented-Object-Detection#53]
![图片](https://user-images.githubusercontent.com/74409617/100425921-0a0c3a80-30cb-11eb-814b-5798108fa035.png)

In training times such error, is the picture cut size incorrect?

**Comment by Arka161** [comment]
I get the same issue. Do you have any input on the fix? Thanks

**Comment by s-s-wang** [comment]
Sorry, I forget, maybe the input should be revised as the corrected form.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yijingru/BBAVectors-Oriented-Object-Detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 晚上7:59
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [yijingru/BBAVectors-Oriented-Object-Detection] RuntimeError: The size of tensor a (15) must match the size of tensor b (5) at non-singleton dimension 1 (#53)





 
I get the same issue. Do you have any input on the fix? Thanks

**Comment by Arka161** [comment]
Thank you for the reply.
Do you mean the input size, or the input images?

Any help would be appreciated :)
Thanks and regards
