### ISSUE TITLE
About the FocalLoss in code

### ISSUE THREAD

**Issue by byfate** [yijingru/BBAVectors-Oriented-Object-Detection#57]
the heatmap branch is used to calculte the loss of the class :
in loss.py
it defines:
pos_inds = gt.eq(1).float()  # equal 1
neg_inds = gt.lt(1).float()   # < 1
so the guassin gt map is not useful any more? It just use the center point.
Could you help me in this puzzlement,appreciated!

**Comment by yijingru** [comment]
`gt.lt(1).float() # < 1` explains

**Comment by byfate** [comment]
After carefully checked the paper,I got it. the positive object only contains the gt center point,and all other points are regared as negavitve,but for the points inside guassian bumps decrease the penalty,thanks you replying.
