### ISSUE TITLE
Confusion about ngpus

### ISSUE THREAD

**Issue by seekFire** [yijingru/BBAVectors-Oriented-Object-Detection#75]
I found that the param **ngpus** did not be conveyed into any pytorch API function, so is it right that the training script will use all gpus by default as long as **ngpus** > 1 ?

**Comment by yijingru** [comment]
https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/12fb6d60bab69c81650fde72291a2c8177c2e338/train.py#L96

**Comment by seekFire** [comment]
> https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/12fb6d60bab69c81650fde72291a2c8177c2e338/train.py#L96

Yes! I have noticed this line of code, but as you know **args.ngpus** did not be conveyed into any pytorch function, it's just given a value...I don't know much about pytorch, but I think it is incredible that you can specify the number of GPUs just through defining a variable...
![ngpus](https://user-images.githubusercontent.com/26456083/112156751-81894b00-8c21-11eb-90f1-7c65ee64362b.png)

**Comment by yijingru** [comment]
It's just an indication of using multi-GPU or not. The variable is for flexible debug.

**Comment by seekFire** [comment]
@yijingru Thank U! I see what you mean. Frankly I have read the code of **yolov5** recently, you know this frame can use multi-gpus to train model. I noticed that their code also exist the question I confused above:
[line 1](https://github.com/ultralytics/yolov5/blob/0d891c601e8178e4b9665da46d630456668b1996/train.py#L470)
[line 2](https://github.com/ultralytics/yolov5/blob/0d891c601e8178e4b9665da46d630456668b1996/train.py#L517)
[line 3](https://github.com/ultralytics/yolov5/blob/0d891c601e8178e4b9665da46d630456668b1996/train.py#L537)
[block](https://github.com/ultralytics/yolov5/blob/0d891c601e8178e4b9665da46d630456668b1996/utils/torch_utils.py#L54-L77)
As you can see, their function **select_device** just return torch.device('cuda:0') whatever the input is, But it does play the function of using the specified GPUs...That's why I rise this issue.
