### ISSUE TITLE
The way predict bounding box with diagnoal line.

### ISSUE THREAD

**Issue by igo312** [yijingru/BBAVectors-Oriented-Object-Detection#86]
@yijingru 
Just for curious, I wanna know why you choose predict the top, left, right and bottom vectors rather than diagnoal line. Is there any mathmatical theory or you just choose this way?

Could you please tell me what you think? Thank you!

**Comment by yijingru** [comment]
I tried diagonal vectors before, they can work but I didn't compare the performances. I think top/left/right/bottom vectors are easier to capture as they locate on the objects.

**Comment by igo312** [comment]
@yijingru thank you for your response.

yes, you are right. From my experiment, the `diagnoal line` is more diffcult to train as the convergence of train loss is slower than `t/l/b/r` method.

But as for mAP I should run it in dota in future. In hrsc, they get similar perfomance.
