### ISSUE TITLE
加载慢或者说没法训练

### ISSUE THREAD

**Issue by yzk-lab** [yijingru/BBAVectors-Oriented-Object-Detection#88]
![image](https://user-images.githubusercontent.com/41197028/120067317-78977880-c0ad-11eb-980c-f4bdd9b13476.png)
作者你好！我用一块2080，batch-size设置为4 试着跑DOTA数据集，一直卡在这里，内存显示占用了9600M，似乎不能成功训练起来是什么原因呢？

**Comment by Fly-dream12** [comment]
同问 数据加载很慢 训练一代时间太长 @yzk-lab @yijingru
