### ISSUE TITLE
测试卡着

### ISSUE THREAD

**Issue by yzk-lab** [yijingru/BBAVectors-Oriented-Object-Detection#89]
作者，你好，感谢你的工作！我想问一个问题，我测试结束保存了模型 为什么 测试的时候一直卡在这。
![image](https://user-images.githubusercontent.com/41197028/120335318-f5cc2300-c323-11eb-920e-2833ac187ae7.png)
这可能是什么原因导致的呢？我看别人测试都是一张一张的测试的，我的一直卡着不动了。

**Comment by Fly-dream12** [comment]
请问这个你是怎么解决的呢   我遇到了测试很慢的问题 @yzk-lab

**Comment by yzk-lab** [comment]
训练慢是正常的，因为DOTA数据集比较大，每一个epoch大概20几分钟，一共80个，大概要一天多一点，能训练起来就不碍事。至于那个测试，我搞错了他的本意，那就只是一个可视化的效果，按任意键可以播放下一张图片的可视化。如果要得到标签就得去main eval方法。我开始折腾了半天，谁想到test和eval被我理解错了，尴尬。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yijingru/BBAVectors-Oriented-Object-Detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月6日(星期天) 上午9:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yijingru/BBAVectors-Oriented-Object-Detection] 测试卡着 (#89)





 
请问这个你是怎么解决的呢   我遇到了测试很慢的问题 @yzk-lab

**Comment by Lg955** [comment]
> 训练慢是正常的，因为DOTA数据集比较大，每一个epoch大概20几分钟，一共80个，大概要一天多一点，能训练起来就不碍事。至于那个测试，我搞错了他的本意，那就只是一个可视化的效果，按任意键可以播放下一张图片的可视化。如果要得到标签就得去main eval方法。我开始折腾了半天，谁想到test和eval被我理解错了，尴尬。

所以那个test就相当于inference；那个eval就是使用DOTA-1.0里面的test数据（没有标签的）进行eval，再把结果提交到DOTA网站得到mAP是吧？

我还有一个疑问：代码中生成的trainval.txt只包含了DOTA-V1.0中的train数据还是把train和val两部分都包含了？因为我在train.py中发现作者并没有在每个epoch训练完之后进行一次验证，那就相当于要把所有epoch的结果都eval一遍提交到DOTA网站才能知道哪个是最好的？

**Comment by yijingru** [comment]
> > 训练慢是正常的，因为DOTA数据集比较大，每一个epoch大概20几分钟，一共80个，大概要一天多一点，能训练起来就不碍事。至于那个测试，我搞错了他的本意，那就只是一个可视化的效果，按任意键可以播放下一张图片的可视化。如果要得到标签就得去main eval方法。我开始折腾了半天，谁想到test和eval被我理解错了，尴尬。
> 
> 所以那个test就相当于inference；那个eval就是使用DOTA-1.0里面的test数据（没有标签的）进行eval，再把结果提交到DOTA网站得到mAP是吧？
> 
> 我还有一个疑问：代码中生成的trainval.txt只包含了DOTA-V1.0中的train数据还是把train和val两部分都包含了？因为我在train.py中发现作者并没有在每个epoch训练完之后进行一次验证，那就相当于要把所有epoch的结果都eval一遍提交到DOTA网站才能知道哪个是最好的？

你也可以拆分一个小的validation数据集进行验证得到最佳的训练procedure，再一起train, 但是可能validation数据分布可能会有bias。

**Comment by Lg955** [comment]
> > 训练慢是正常的，因为DOTA数据集比较大，每一个epoch大概20几分钟，一共80个，大概要一天多一点，能训练起来就不碍事。至于那个测试，我搞错了他的本意，那就只是一个可视化的效果，按任意键可以播放下一张图片的可视化。如果要得到标签就得去main eval方法。我开始折腾了半天，谁想到test和eval被我理解错了，尴尬。

> 
> 你也可以在validation数据集进行验证得到最佳的训练procedure，再一起train

OK
