### ISSUE TITLE
Training from scratch = no detections 

### ISSUE THREAD

**Issue by Mantha27** [yijingru/BBAVectors-Oriented-Object-Detection#90]
Hello,

Everything works perfectly when using the pretrained weights downloaded from Dropbox.
However, when training from scratch or resume training (on DOTA) and then running test or eval, the detections are always empty. They do not show on the image nor do any results appear in the merge_dota or results_dota txt files.

Do you know how I could solve this issue?

Thank you

**Comment by kleinicke** [comment]
You could lower the confidence threshhold (a commandline argument --conf_thresh).
It might be too high, if the network is more uncertain with it's predictions.

**Comment by Mantha27** [comment]
Thank you for your reply, I tried this but it didn't change anything unfortunately.

**Comment by yijingru** [comment]
Did you use the 600x600 cropped images?
