### ISSUE TITLE
two typos in the code

### ISSUE THREAD

**Issue by kleinicke** [yijingru/BBAVectors-Oriented-Object-Detection#91]
I've found two issues in the code.
In the function imshow_heatmap in test.py variable pr_decs is used, but only pr_dec is defined.

In the data_transform function in datasets/base.py the line
`image, gt_pts, crop_center = random_flip(image, annotation['pts'], crop_center)`
returns gt_pts, which are not used. Maybe it should be written back to annotation['pts']?

(by the way with a git amend commit, you can commit additional changes to the last performed commit. This is useful if you forgot just something small in the last commit. If that commit was already pushed, a force push is required to update the repo upstream.)

**Comment by yijingru** [comment]
Thanks for your help! Those issues are corrected.
