### ISSUE TITLE
NMS 

### ISSUE THREAD

**Issue by Mantha27** [yijingru/BBAVectors-Oriented-Object-Detection#95]
Hello,
Does this use NMS and/or is there a way I can change the NMS threshold, I'm getting quite a few detections on the same object (custom dataset) and think this may be a way to reduce it.

Thanks for you help!

**Comment by yijingru** [comment]
You may want to check here https://github.com/yijingru/BBAVectors-Oriented-Object-Detection/blob/7efd410f5f4ded94aca986aeb0bd1292235d1314/func_utils.py#L89
